name = "Create Central"
author = "sploosh"
version = "1.0.0"
description = "Create and its best addons on NeoForge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32b02e6e6a8e255eb1ded383c11e5a9a155aa781d4b3d1cf4ff33b15f489ea16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
