name = "Create Central"
author = "sploosh"
version = "1.0.0"
description = "Create and its best addons on NeoForge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511985a8b7d51ebaf92255428bf89a609c0e7502ebe2754bb5d53adde15ca249"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
