name = "Create Central"
author = "sploosh"
version = "1.0.0"
description = "Create and its best addons on NeoForge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4590e582a777daeb5bdece01f2f7d5001658033a1d7fadafe7748e0823a080b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
